name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  schedule:
    # Каждую среду в 12:30
    - cron: '30 12 * * 3'
    # Каждую пятницу в 22:00
    - cron: '0 22 * * 5'

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        java: [ 11, 13, 17 ]
        distribution: ${{ matrix.java == '13' && 'zulu' || 'temurin' }}

    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    steps:
    - name: download the code
      uses: actions/checkout@v4
    - name: Set up JDKs
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: ${{ matrix.distribution }}
    - name: Make gradlew executable
      if: runner.os != 'Windows'
      run: chmod +x gradlew
    - name: Build with Gradle Wrapper and test
      run: ./gradlew build
